/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-02-03 at 22:14:26 UTC 
 * Modify at your own risk.
 */

package com.appspot.recognize_1210.recognize.model;

/**
 * Model definition for RecognizeAlbumMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recognize. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RecognizeAlbumMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("album_id") @com.google.api.client.json.JsonString
  private java.lang.Long albumId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("album_type")
  private java.lang.String albumType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String category;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<RecognizeQuestionMessage> questions;

  static {
    // hack to force ProGuard to consider RecognizeQuestionMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(RecognizeQuestionMessage.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAlbumId() {
    return albumId;
  }

  /**
   * @param albumId albumId or {@code null} for none
   */
  public RecognizeAlbumMessage setAlbumId(java.lang.Long albumId) {
    this.albumId = albumId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAlbumType() {
    return albumType;
  }

  /**
   * @param albumType albumType or {@code null} for none
   */
  public RecognizeAlbumMessage setAlbumType(java.lang.String albumType) {
    this.albumType = albumType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategory() {
    return category;
  }

  /**
   * @param category category or {@code null} for none
   */
  public RecognizeAlbumMessage setCategory(java.lang.String category) {
    this.category = category;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public RecognizeAlbumMessage setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<RecognizeQuestionMessage> getQuestions() {
    return questions;
  }

  /**
   * @param questions questions or {@code null} for none
   */
  public RecognizeAlbumMessage setQuestions(java.util.List<RecognizeQuestionMessage> questions) {
    this.questions = questions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public RecognizeAlbumMessage setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public RecognizeAlbumMessage set(String fieldName, Object value) {
    return (RecognizeAlbumMessage) super.set(fieldName, value);
  }

  @Override
  public RecognizeAlbumMessage clone() {
    return (RecognizeAlbumMessage) super.clone();
  }

}
