/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-02-03 at 22:14:26 UTC 
 * Modify at your own risk.
 */

package com.appspot.recognize_1210.recognize.model;

/**
 * Model definition for RecognizeQuestionMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recognize. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RecognizeQuestionMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fact;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<RecognizeImageMessage> images;

  static {
    // hack to force ProGuard to consider RecognizeImageMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(RecognizeImageMessage.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("question_id") @com.google.api.client.json.JsonString
  private java.lang.Long questionId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFact() {
    return fact;
  }

  /**
   * @param fact fact or {@code null} for none
   */
  public RecognizeQuestionMessage setFact(java.lang.String fact) {
    this.fact = fact;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<RecognizeImageMessage> getImages() {
    return images;
  }

  /**
   * @param images images or {@code null} for none
   */
  public RecognizeQuestionMessage setImages(java.util.List<RecognizeImageMessage> images) {
    this.images = images;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getQuestionId() {
    return questionId;
  }

  /**
   * @param questionId questionId or {@code null} for none
   */
  public RecognizeQuestionMessage setQuestionId(java.lang.Long questionId) {
    this.questionId = questionId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public RecognizeQuestionMessage setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public RecognizeQuestionMessage set(String fieldName, Object value) {
    return (RecognizeQuestionMessage) super.set(fieldName, value);
  }

  @Override
  public RecognizeQuestionMessage clone() {
    return (RecognizeQuestionMessage) super.clone();
  }

}
